name: spotify
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_database: ^10.2.7
  cloud_firestore: ^4.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-Bold.ttf
        - asset: fonts/Caveat-Medium.ttf
        - asset: fonts/Caveat-Regular.ttf
        - asset: fonts/Caveat-SemiBold.ttf

    - family: Gotham
      fonts:
        - asset: fonts/GothamLight.ttf
          weight: 300
        - asset: fonts/GothamBook.ttf
          weight: 400
        - asset: fonts/GothamMedium.ttf
          weight: 500
        - asset: fonts/GothamBold.ttf
          weight: 600

    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
